- name: create system user
  ansible.builtin.user:
    name: roboshop
    state: present
    shell: /usr/sbin/nologin
    comment: "roboshop system user"
    home: /app
    system: true
  # Safe to remove directory, because 2nd time if we run it will download freshly. no error if does not exist
- name: remove directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: remove {{ componet }} file
  ansible.builtin.file:
    path: /tmp/{{ componet }}.zip 
    state: absent

- name: create app direcrtory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download {{ componet }} applications
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ componet }}-v3.zip 
    dest: /tmp/{{ componet }}.zip 

- name: extract  application
  ansible.builtin.unarchive:
    src: /tmp/{{ componet }}.zip 
    dest: /app
    remote_src: yes
